### PR TITLE
Add certificate test to API

### PR DESCRIPTION
**Pull request by pmandrik**
Fix readme recipe to work on lxplus7 & add enable SSL verification since it seems to be fixed in cernrequest.

### CODE REVIEW

**Comment by pmandrik** [comment]
Hello, @jfernan2 ,

for the test I think we need to provide cms-DQM with secrets.DOCKERHUB_USERNAME and secrets.DOCKERHUB_TOKEN used in:
https://github.com/cms-DQM/runregistry/blob/master/.github/workflows/build-and-push.yml

they could be added following:
https://docs.github.com/en/actions/security-guides/encrypted-secrets

the login/password probably for hub.docker.com where e.g. https://hub.docker.com/r/cmssw/runregistry-frontend/ is hosted.
Probably, as Fabio pushed to the docker from his account now we need to create different docker image, e.g. https://hub.docker.com/r/cmssw/runregistry-frontend2/ to perform tests

**Comment by jfernan2** [comment]
OK, thanks.
However, I am not sure which accounrt should be used to log in into hub.docker.com
And I also see that fabio has pussed an image to the docker 6 days ago:
https://hub.docker.com/r/cmssw/runregistry-frontend/tags
@fabioespinosa   could you comment?

**Comment by fabioespinosa** [comment]
Hi all,

Sorry for my late reply. I haven't pushed anything to docker hub. But I read there's a new service from CERN to publish images, and they might need to be rebuilt.

If I remember correctly, the microservice to ping DQM GUI should be running continually (it's just a cron job) and its just one file. 

However, the one for fetching runs is still incorporated into the API so no need to create a microservice for that, however it would be nice to separate them at some point. In the code they are separated for this to eventually happen.

We also use Redis for queuing the processing of jsons and so we need a microservice to have an instance of redis, although we don't care about persisting it, if for some reason we lose the data inside the redis pod, the worse that can happen is that we lose the process of whoever was creating a 'golden' json in that specific moment, all finished jsons are saved in the DB, so this one is completely ephemeral.

And I think that should be it.

**Comment by fabioespinosa** [comment]
> Hello, @jfernan2 ,
> 
> for the test I think we need to provide cms-DQM with secrets.DOCKERHUB_USERNAME and secrets.DOCKERHUB_TOKEN used in: https://github.com/cms-DQM/runregistry/blob/master/.github/workflows/build-and-push.yml
> 
> they could be added following: https://docs.github.com/en/actions/security-guides/encrypted-secrets
> 
> the login/password probably for hub.docker.com where e.g. https://hub.docker.com/r/cmssw/runregistry-frontend/ is hosted. Probably, as Fabio pushed to the docker from his account now we need to create different docker image, e.g. https://hub.docker.com/r/cmssw/runregistry-frontend2/ to perform tests

Oh and regarding this, the secrets are stored in here: https://github.com/cms-DQM/runregistry/settings/secrets/actions

Right now whoever makes a push to master, will trigger an event that will try to push the image to dockerhub, that's why it seems I made a push. But it was probably just a commit that got merged into master which triggered this workflow.

**Comment by jfernan2** [comment]
Hi guys, so let me see if I get all this correctly, lease correct me if I am wrong:

If we merge this PR, a docker image will be pushed to https://hub.docker.com/r/cmssw/runregistry-frontend/
but we are not testing it in advance on a automated way with github?
Thanks

**Comment by pmandrik** [comment]
Hi, @jfernan2 , 
probably the workflow is not triggered correctly because "Secrets are not passed to workflows that are triggered by a pull request from a fork." for safety reason.
Possible solution will require some additional works: 
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by jfernan2** [comment]
If you think it is feasible, please go ahead!! Thanks

**Pull request merged**
